### ISSUE TITLE
Ubuntu 24.04

### ISSUE THREAD

**Issue by Sinahosseinian** [bepass-org/oblivion-desktop#361]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام وقت بخیر من روی نسخه ی اوبونتو ۲۴.۰۴ که نصب میکنم نصب میشه ولی اجرا نمیشه فکر کنم باهاش زیاد اوکی نیست چک میکنین.

### Relevant log output | لاگ برنامه

```shell
هیچ عکس العملی موقع ران کردن نمیده من روی اوبونتو 22.04 تست کردم اوکی بود و کار میکرد ولی رو نسخه 24.04 جواب نیست
```

**Comment by kiomarzsss** [comment]
وقتی دستور `oblivion-desktop` رو داخل محیط ترمینال اجرا میکنین چه خروجی ای میده؟

**Comment by usermp** [comment]
> وقتی دستور `oblivion-desktop` رو داخل محیط ترمینال اجرا میکنین چه خروجی ای میده؟

oblivion-desktop
LaunchProcess: failed to execvp:
/opt/Oblivion
[8111:0626/123601.293887:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)

**Comment by Sinahosseinian** [comment]
دقیقا همین ارور که دوستمون فرستاده برای منم میده

**Comment by MJThe52hzwhale** [comment]
منم دقیقا همین خروجی رو دارمتو ترمینال. (اوبونتو ۲۴.۰۴)
تو نصب ارور نمیده اما وقتی میخوای اولین بار اجراش کنی صرفا کرش میخوره و اصلا بالا نمیاد

**Comment by papampi** [comment]
Check: https://github.com/bepass-org/oblivion-desktop/issues/338

**Comment by usermp** [comment]
`oblivion-desktop  --no-sandbox`

**Comment by usermp** [comment]
`sudo nano /usr/share/applications/oblivion-desktop.desktop`

And add `--no-sandbox`

`
Exec="/opt/Oblivion Desktop/oblivion-desktop" --no-sandbox %U
`

**Comment by hosseinabadii** [comment]
منم همین مشکل رو دارم
![Screenshot from 2024-07-01 15-43-15](https://github.com/bepass-org/oblivion-desktop/assets/130921682/18db0a31-2096-4507-9743-fa8aac140443)

**Comment by asady** [comment]
به نظر میرسه مشکل از chrome-sandbox  هست

$ oblivion-desktop
[74685:0403/190633.494284:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/oblivion-desktop/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)


احتمالا با دو دستور زیر حل میشه 

sudo chown root:root /opt/oblivion-desktop/chrome-sandbox
sudo chmod 4755 /opt/oblivion-desktop/chrome-sandbox
