### ISSUE TITLE
W.A.R.P+ key use

### ISSUE THREAD

**Issue by Speed5263** [bepass-org/oblivion-desktop#490]
### Feature description | توضیحات ویژگی

the official warp app from cloudflare has a warp+ subscription pretty cheap if you get it you can use your warp+ key on other devices upto a maximum of 5 so is there a way to use this on oblivion or can this feature be implemented

**Comment by ircfspace** [comment]
This feature is available in Oblivion Desktop, allowing you to use Warp licenses. However, since Warp-Plus in the current version doesn't provide detailed information about each license's status, using it might be a bit confusing. The Warp-Plus developers have promised to improve this situation in future updates. Nevertheless, to use this feature, go to the Oblivion Desktop settings, navigate to the Warp settings tab, and then proceed to the License section.
