### ISSUE TITLE
I can't login from my Qnap qfinder pro

### ISSUE THREAD

**Issue by mingjkli** [bepass-org/oblivion-desktop#569]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

After installing this software, I find that there is an error popup from my software qfinder pro. I login to my Qnap NAS with webpage have no problem at all but when I use qfinder pro to find my NAS it shows that I can't reach the same ip: 192.168.1.8 that my NAS fix ip. Why I make sure is your software to create this problem? Because I use my laptop to try the same with qfinder pro login and it becomes no problem at all without installing your software. Even I uninstalled your software with uninstaller pro and deleted all registry but it is no help for the above problem, please help me to solve this and then I will not need to reinstall my Windows. Thanks for your help in advance.
![2024-10-04 195103](https://github.com/user-attachments/assets/f17452df-9e6e-4734-8e9d-7da587ebebee)

### Relevant log output | لاگ برنامه

```shell
I havent copied it, sorry!
```

**Comment by mingjkli** [comment]
I think as a developer, even you can't find any such same problem, do you think you will help to find any possibe of your software to let this problem happened? If your answer is you will do nothing about it, ok I will tell others to take a look of it and try as their own risk!!!!

**Comment by ircfspace** [comment]
Hello,  
This issue might be due to your entire system not being tunneled. 
We are currently working on the TUN feature, which will be available in [version 2.](https://github.com/bepass-org/oblivion-desktop/issues/532) 
At the moment, only the browser, Telegram app, and a few other programs pass through Warp in system proxy mode, which is likely the reason for your issue. If you can, please wait for version 2, or in the meantime, you can use software like [Nekoray](https://github.com/bepass-org/oblivion-desktop/wiki/TUN-with-nekoray) to tunnel the whole system.
