### ISSUE TITLE
Changing system proxy setting after successfully connecting not before that!

### ISSUE THREAD

**Issue by morealaz** [bepass-org/oblivion-desktop#640]
### Feature description | توضیحات ویژگی

Hi,
Currently oblivion change system proxy setting when clicking on connect bottom before establishing a successful connection (correct me if I'm wrong), and this interrupts some apps that currently connected to internet due to proxy not working while oblivion trying to connect.
It would be better to set proxy setting after successfully establishing a connection.

**Comment by ircfspace** [comment]
Hello,  
Thank you for your feedback.  

As you know, the Oblivion Desktop application is a GUI for Warp-Plus, and the connection through Warp-Plus itself can be time-consuming. This means the user has to wait for a period of time for the IP to be scanned and the connection to be established. The action of applying proxy settings when clicking the connect button was implemented in order to minimize the final delay for the user and reduce the impact on the user experience.
